from __future__ import annotations
import logging
import time
from typing import Any, Dict, Optional

from config import settings

logger = logging.getLogger("smartschool.auth")
_invite_codes: Dict[str, Dict[str, Any]] = {}

def store_invite_code(
    code: str,
    camera_id: str,
    generated_by: str,
) -> float:
    expires_at = time.time() + settings.invite_code_ttl
    _invite_codes[code] = {
        "expires_at": expires_at,
        "generated_by": generated_by,
        "camera_id": camera_id,
    }
    logger.info(
        "Invite code generated by %s for camera %s (expires %.0fs)",
        generated_by, camera_id, settings.invite_code_ttl,
    )
    return expires_at


def validate_invite_code(code: str) -> Optional[Dict[str, Any]]:
    data = _invite_codes.get(code)
    if data is None:
        return None
    if time.time() > data["expires_at"]:
        _invite_codes.pop(code, None)
        return None
    return data

def consume_invite_code(code: str) -> None:
    _invite_codes.pop(code, None)

ROLE_PERMISSIONS: Dict[str, set] = {
    "moderator": {
        "xto_ya", "login", "logout", "register",
        "init", "camera","site_inf",
        "manage_account", "generate_invite_code",
        "get_json_files", "get_json_content",
        "spisok_inf", "get_stats", "get_people", "grafiki",
    },
    "user": {
        "xto_ya", "login", "logout",
        "get_stats", "get_people", "spisok_inf", "grafiki",
    },
    "camera": {
        "camera", "init",
    },
}

PUBLIC_ACTIONS = {"login", "register", "xto_ya"}
def check_permission(role: Optional[str], action: str) -> bool:
    if action in PUBLIC_ACTIONS:
        return True
    if role is None:
        return False
    return action in ROLE_PERMISSIONS.get(role, set())